Imports
```{r}
library(malecns)
library(coconatfly)
library(fafbseg)
library(neuprintr)

library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(stringr)
library(igraph)
library(tidygraph)
library(ggraph)
library(jsonlite)
library(ggplot2)
library(reshape2)
library(Matrix)

conna = neuprint_login(dataset='male-cns:v0.9',server='https://neuprint-cns.janelia.org/')
mcns.rois = neuprint_ROIs(dataset = 'male-cns:v0.9')
neuprint_get_synapses(13693,roi='VNC')
setwd("/Users/fkampf/Documents/mcns.ccs/effective.connectivity.ccs/effective.connectivity.ccs.path.simulated.activity")
```

```{r setup, include=FALSE}
# Setup knitr global options for clean rendering and consistent figures
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = 'center',
  fig.width = 8,
  fig.height = 6
)
```


## 1 Load data

### 1.1 Load male boday annotations
```{r}
synapse_threshold=5
mba<-mcns_body_annotations()
mba.static<-mcns_body_annotations()
mba<-mba%>%mutate(type=ifelse(type=='',NA,type))

list.fcell <- mba.static%>%filter(receptor_type=="putative_ppk25")%>%pull(type)%>%unique()
list.mcell <- mba.static%>%filter(receptor_type=="putative_ppk23")%>%pull(type)%>%unique()
list.ir52a <- mba.static%>%filter(receptor_type=="putative_IR52a")%>%pull(type)%>%unique()
list.ir52b <- mba.static%>%filter(receptor_type=="putative_IR52b")%>%pull(type)%>%unique()

mba <- mba %>%
  mutate(
    type = case_when(
      type %in% list.mcell ~ "m-cell",
      type %in% list.fcell ~ "f-cell",
      type %in% list.ir52a ~ "ir52a-cell",
      type %in% list.ir52b ~ "ir52b-cell",
      TRUE ~ type
    )
  )
```

### 1.2 Function to load connectivity
```{r}
fetch_connectivity <- function(synapse_threshold = 5) {
  mba <- mcns_body_annotations()
  connectivity <- cf_partners(cf_ids(malecns = mba %>% pull(bodyid)),
                              partners = 'o',
                              threshold = synapse_threshold)
  connectivity <- connectivity %>%mutate(pre_id=as.double(pre_id),post_id=as.double(post_id))
  connectivity <- connectivity %>%
    left_join(mba %>%
                select("type", "bodyid",'fru_dsx','consensus_nt','flywire_type','synonyms','receptor_type') %>%
                rename(pre_type = type,pre_fru_dsx=fru_dsx,pre_nt=consensus_nt,pre_fw_type=flywire_type,pre_synonyms=synonyms,pre_receptor_type=receptor_type),
              by = c('pre_id'='bodyid'))%>%
    rename(post_type = type)%>%
    left_join(mba %>%
                select("bodyid",'fru_dsx','consensus_nt','flywire_type','synonyms','receptor_type') %>%
                rename(post_fru_dsx=fru_dsx,post_nt=consensus_nt,post_fw_type=flywire_type,post_synonyms=synonyms,post_receptor_type=receptor_type),
              by = c('post_id'='bodyid'))
  return(connectivity)
}
```

### 1.3 Load connectivity
```{r}
conn <-fetch_connectivity()



conn <- conn %>%
  mutate(
    pre_type = case_when(
      pre_type %in% list.mcell ~ "m-cell",
      pre_type %in% list.fcell ~ "f-cell",
      pre_type %in% list.ir52a ~ "ir52a-cell",
      pre_type %in% list.ir52b ~ "ir52b-cell",
      TRUE ~ pre_type
    ),
    post_type = case_when(
      post_type %in% list.mcell ~ "m-cell",
      post_type %in% list.fcell ~ "f-cell",
      post_type %in% list.ir52a ~ "ir52a-cell",
      post_type %in% list.ir52b ~ "ir52b-cell",
      TRUE ~ post_type
    )
  )
conn_save <- conn
```

## 2 Adjacency matrix
### 2.1 Function adjacency matrix
```{r}
calculate_normed_adj_matrix <-function(connectivity,cell.or.type='type',pre.or.post='pre'){
  colScale <- function(A, na.rm = TRUE) {
    scalefac <- 1 / Matrix::colSums(A)
    if (na.rm) scalefac[!is.finite(scalefac)] <- 0
    B <- A %*% Matrix::Diagonal(x = scalefac)
    B
    }
  rowScale <- function(A, na.rm = TRUE) {
    scalefac <- 1 / Matrix::rowSums(A)
    if (na.rm) scalefac[!is.finite(scalefac)] <- 0
    B <- Matrix::Diagonal(x = scalefac) %*% A
    B
    }
  if(cell.or.type=='cell'){
    unique.identifier <- union(as.character(connectivity$pre_id), as.character(connectivity$post_id))
    adj.matrix <- sparseMatrix(
      i = match(connectivity$pre_id, unique.identifier),
      j = match(connectivity$post_id, unique.identifier),
      x = connectivity$weight,
      dims = c(length(unique.identifier), length(unique.identifier)),
      dimnames = list(unique.identifier, unique.identifier))
  }else{
    unique.identifier <- union(connectivity$pre_type, connectivity$post_type)
    adj.matrix <- sparseMatrix(
      i = match(connectivity$pre_type, unique.identifier),
      j = match(connectivity$post_type, unique.identifier),
      x = connectivity$weight,
      dims = c(length(unique.identifier), length(unique.identifier)),
      dimnames = list(unique.identifier, unique.identifier))
  }
  if(pre.or.post=='pre'){
    adj.matrix.normed.pre <- rowScale(adj.matrix)
    colnames(adj.matrix.normed.pre) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.pre) <- rownames(adj.matrix)
    return(adj.matrix.normed.pre)
  }else{
    adj.matrix.normed.post <- colScale(adj.matrix)
    colnames(adj.matrix.normed.post) <- colnames(adj.matrix)
    rownames(adj.matrix.normed.post) <- rownames(adj.matrix)
    return(adj.matrix.normed.post)
  }
}
```

### 2.1 Create adjacency matrix
```{r}
conn <-conn_save
conn <- conn%>%
  mutate(pre_type=coalesce(pre_type,pre_fw_type),post_type=coalesce(post_type,post_fw_type))%>%
  mutate(pre_type=if_else(is.na(pre_type),as.character(bodyid),pre_type),
         post_type=if_else(is.na(post_type),as.character(partner),post_type))




nam <-calculate_normed_adj_matrix(conn,cell.or.type='type',pre.or.post='post')

nam_thresholded <-nam

g.prout.mcns <- graph_from_adjacency_matrix(
  nam_thresholded,
  mode = "directed",
  weighted = TRUE,
  diag = FALSE
)
```


Targets
```{r}
#starts
start_types <- cf_partners(cf_ids(malecns = mba%>%
                                   filter(type %in% c('AN05B102','AN09B017'))%>%
                                   pull(bodyid)%>%
                                   unique()),
                          partners='i',threshold=5)%>%
  left_join(mba%>%select(receptor_type,bodyid),by=c('partner'='bodyid'))%>%
  mutate(
    type = case_when(
      type %in% list.mcell ~ "m-cell",
      type %in% list.fcell ~ "f-cell",
      type %in% list.ir52a ~ "ir52a-cell",
      type %in% list.ir52b ~ "ir52b-cell",
      TRUE ~ type
    )
  )%>%
  filter(superclass=='vnc_sensory')%>%
  filter(!is.na(type))%>%
  pull(type)%>%
  unique()



#targets
SAG <- 'ANXXX150'
P1 <- mba %>% filter(grepl("P1_",type))%>%pull(type)%>%unique()
TK <- mba %>% filter(grepl("TK-FruM",synonyms))%>%pull(type)%>%unique()
pCd <- mba %>% filter(grepl("pCd",synonyms))%>%pull(type)%>%unique()
pMP2 <- 'pMP2'
pIP10 <- 'pIP10'
CL062 <- mba %>% filter(grepl("CL062",type))%>%pull(type)%>%unique()
 
target_types <- c(P1,TK,pCd,pMP2,pIP10)
```


path finding new


```{r}

# Define parameters for path search
n_paths <-  1       # Number of strongest paths to find for each start-target pair
diversity <- 'otheredges'  # othernodes,otheredges,none

# Your existing code
cell_types <- c('CB1076','CB1078', 'CB3710', 'CB2521','CB1542', 'CB1038', 'CB1427', 'CB2556a', 'CB2380') #all
cell_types <- c('(JO-B)') #only JO-B

cell_types <- c('f-cell','m-cell','AN09B017','AN05B102')
cell_types <- c('CB1542','CB1078')
cell_types <- start_types

target_cells <- c("vpoEN",'CB1385',"vpoEN",'CB1385')  # List of target cells
target_cells <- c(target_cells,'pMP2')
target_cells <- c(target_cells,mba%>% filter(grepl('aSP-k',synonyms))%>%filter(!is.na(type))%>%pull(type)%>%unique())
target_cells <- c('pIP10','pMP2')
target_cells <- target_types



#target_cells <- c(target_cells,V(g.prout.mcns)$name[grepl("P1_", V(g.prout.mcns)$name)])
#target_cells <- c(all.levels.prout.mcns.output%>%filter((post_type=='vpoEN')&(weight>=0.1))%>%pull(pre_type)%>%unique(),target_cells)

# Transform weights using log
E(g.prout.mcns)$log_weight <- -log(E(g.prout.mcns)$weight)  # Negate to convert to shortest path problem



# Initialize an empty list to store results and a vector for important nodes
results <- list()
all_important_nodes <- character()

# Loop over all start (cell_types) and target (target_cells) pairs
for (start in cell_types) {
  for (end in target_cells) {

    # Only process if both start and end exist in the graph
    if ((start %in% V(g.prout.mcns)$name) && (end %in% V(g.prout.mcns)$name)) {

      # Make a copy of the graph to modify iteratively
      g_temp <- g.prout.mcns
      
      # List to hold all paths for this start–end pair
      pair_paths <- list()
      
      # Find up to 'n_paths' for the given pair
      for (i in 1:n_paths) {
        # Compute shortest path (using negative log weights so that lower is stronger)
        path_result <- shortest_paths(g_temp, from = start, to = end,
                                      weights = E(g_temp)$log_weight,
                                      output = "both")
        
        # Check if a path was found
        if (length(path_result$vpath[[1]]) > 0) {
          path_nodes <- path_result$vpath[[1]]
          path_edges <- path_result$epath[[1]]
          # Convert back to strength: reverse the -log transform
          final_strength <- exp(-sum(E(g_temp)[path_edges]$log_weight))
          
          # Save the results; note that we display the path using the names from the original graph
          pair_paths[[paste0("path", i)]] <- list(
            start = start,
            end = end,
            path = paste(V(g.prout.mcns)[path_nodes]$name, collapse = " -> "),
            strength = final_strength
          )
          # Collect nodes from this path into the overall list
          all_important_nodes <- c(all_important_nodes, V(g.prout.mcns)[path_nodes]$name)
          
          # Modify the temporary graph to seek a different path next time
          if (diversity=='othernodes') {
            # Remove intermediate nodes (all nodes except the start and end)
            intermediate_nodes <- V(g.prout.mcns)[path_nodes]$name  # get names from the original graph
            nodes_to_remove <- setdiff(intermediate_nodes, c(start, end))
            if (length(nodes_to_remove) > 0) {
              g_temp <- delete_vertices(g_temp, nodes_to_remove)
            }
          } else if(diversity=='otheredges'){
            # Remove the edges used in this path so that the next path will be different
            g_temp <- delete_edges(g_temp, path_edges)
          }else{
            1+1
          }
            
        } else {
          # If no further path is found, break out of the inner loop
          break
        }
      }
      # Save all the paths found for this start–end pair into the results list
      results[[paste(start, end, sep = "->")]] <- pair_paths
    } else {
      # If either node doesn't exist, store an NA entry for this pair
      results[[paste(start, end, sep = "->")]] <- list(list(
        start = start,
        end = end,
        path = NA,
        strength = NA
      ))
    }
  }
}

# Flatten the nested results list into a single data frame for easier inspection:
results_df <- do.call(rbind, lapply(results, function(pair_list) {
  do.call(rbind, lapply(pair_list, function(r) {
    data.frame(
      start = r$start,
      end = r$end,
      path = r$path,
      strength = r$strength,
      stringsAsFactors = FALSE
    )
  }))
}))

# (Optional) Get unique important nodes encountered in all the paths:
all_important_nodes <- unique(all_important_nodes)
results_df_wo_na <- results_df%>%
  filter(!is.na(strength))
# Look at the results
print(results_df_wo_na)
```






Open graph in RCy3

```{r}
library(RCy3)
library(dplyr)


nodes_to_keep <- c("JO-B","JO-B",'CB1078','CB1542','CB2108','CB1383','CB1066,CB3649
','CB2364','CB3382','PVLP033','CB3162','CB3382','vpoEN','SIP124m',
'AVLP721m','AVLP299_c','DNp55','CB1385','AVLP711m','SIP108m','SIP120m','SIP116m','SIP114m','PVLP211m','pMP2','AVLP744m')
nodes_to_keep <- c(nodes_to_keep,unique(all_important_nodes))
nodes_to_keep <-unique(all_important_nodes)

#add P1 only to neurons which would be in the graph anyway
#P1_2_add <- conn%>%
#  filter(pre_type %in% nodes_to_keep,
#         grepl("^P1_", post_type))%>%
#  pull(post_type)%>%
#  unique()

#nodes_to_keep<-c(nodes_to_keep,P1_2_add)

#cleaning up graph and subsampling

g.sub.prout.mcns <- induced_subgraph(g.prout.mcns, vids = V(g.prout.mcns)[name %in% nodes_to_keep])


nodes_to_filter <- V(g.sub.prout.mcns)[grepl("^P1_", name)]
try(edges_to_delete <- incident(g.sub.prout.mcns, nodes_to_filter, mode = "out"),silent=T)
try(g.sub.prout.mcns <- delete_edges(g.sub.prout.mcns, edges_to_delete),silent=T)



node_names <- V(g.sub.prout.mcns)$name

distance_to_start <- shortest.paths(g.sub.prout.mcns, to = V(g.sub.prout.mcns)[name %in% cell_types], weights = NA)

V(g.sub.prout.mcns)$distance_to_start <- ifelse(node_names %in% start_types, 0, as.integer(distance_to_start))

try(fru_dsx_values <- conn %>%
    group_by(pre_type,post_type) %>%
    mutate(pre_fru_dsx = !is.na(pre_fru_dsx),
           post_fru_dsx = !is.na(post_fru_dsx))%>%
    summarize(pre_fru_dsx = first(pre_fru_dsx),
              post_fru_dsx = first(post_fru_dsx)) %>%
    ungroup()%>%
    pivot_longer(
        cols = c(pre_fru_dsx, post_fru_dsx, pre_type, post_type),
        names_to = c("side",".value"),  # .value tells pivot_longer to use part of the name as the output column name
        names_sep = "_"                # splits the column names at the underscore
    ) %>%select(-side)%>%distinct())




nt_values <- conn %>%
    group_by(pre_type,post_type) %>%
    mutate(pre_nt = first(pre_nt),
           post_nt = first(post_nt))%>%
    summarize(pre_nt = first(pre_nt),
              post_nt = first(post_nt)) %>%
    ungroup()%>%
    pivot_longer(
        cols = c(pre_nt, post_nt, pre_type, post_type),
        names_to = c("side",".value"),  # .value tells pivot_longer to use part of the name as the output column name
        names_sep = "_"                # splits the column names at the underscore
    ) %>%select(-side)%>%distinct()


try(nt_for_vertices <- nt_values$nt[match(V(g.sub.prout.mcns)$name, nt_values$type)])
try(fru_dsx_for_vertices <- fru_dsx_values$fru[match(V(g.sub.prout.mcns)$name, fru_dsx_values$type)])

V(g.sub.prout.mcns)$nt <- nt_for_vertices
try(V(g.sub.prout.mcns)$fru_dsx <- fru_dsx_for_vertices)

el<- as_edgelist(g.sub.prout.mcns)
is_p1p1 <- grepl("^P1_", el[, 1]) & grepl("^P1_", el[, 2])
E(g.sub.prout.mcns)$is_p1_p1 <- is_p1p1

rename_dict <- list(
  "CB1078" = "aPN1/CB1078",
  "CB1542" = "aPN1/CB1542",
  "CB3382" = "aIP-g/CB3382",
  "CB2364" = "aSP-K/CB2364",
  'AVLP721m' = 'vPN1/AVLP721m',
  "AVLP299_c" = "aIP-b/AVLP299_c",
  "SIP114m" = "aSP-a/SIP114m",
  'SIP116m' = 'aSP-a/SIP116m',
  "SIP120m" = "aSP-a/SIP120m",
  "PVLP211m" = "pIP-e/PVLP211m",
  'AVLP744m' = 'pIP-e/AVLP744m',
  'SIP108m'='pIP-e/SIP108m',
  'AVLP711m'='pIP-e/AVLP711m',
  'CB1385' = 'vpoIN_CB1385',
  'AVLP755m'='AVLP755m/aSP-k/aSP8/LC1',
  'LHAV4c2'='LHAV4c2/aSP-k/aSP8/LC1',
  'AVLP734m'='AVLP734m/aSP-k/aSP8/LC1',
  'ICL008m'='ICL008m/aSP-k/aSP8/LC1',
  'AVLP760m'='AVLP760m/aSP-k/aSP8/LC1'
  
)


# Apply the dictionary to rename the vertices in the graph
V(g.sub.prout.mcns)$name <- sapply(V(g.sub.prout.mcns)$name, function(x) ifelse(x %in% names(rename_dict), rename_dict[[x]], x))


E(g.sub.prout.mcns)$weight<-E(g.sub.prout.mcns)$weight*100

#clean up edges 




important.neurons.list <- c('AN09B017','AN05B102')
repeat {
  prev_edges    <- ecount(g.sub.prout.mcns)
  prev_vertices <- vcount(g.sub.prout.mcns)

  # 1. Delete weak edges only if their source is not in important_neuron
  weak_edges <- E(g.sub.prout.mcns)[ 
    weight < 4 & 
    ! (ends(g.sub.prout.mcns, E(g.sub.prout.mcns))[,1] %in% important.neurons.list)
  ]
  if (length(weak_edges)) {
    g.sub.prout.mcns <- delete_edges(g.sub.prout.mcns, weak_edges)
  }
  
  g.sub.prout.mcns <- delete_edges(
    g.sub.prout.mcns,
    E(g.sub.prout.mcns)[ weight < 1 ]
  )
  

  # 2. Delete all vertices with no remaining edges
  g.sub.prout.mcns <- delete_vertices(
    g.sub.prout.mcns,
    V(g.sub.prout.mcns)[ degree(g.sub.prout.mcns) == 0 ]
  )

  # 3. Keep only vertices with in‐degree > 0 or in start_types
  g.sub.prout.mcns <- induced_subgraph(
    g.sub.prout.mcns,
    vids = V(g.sub.prout.mcns)[
      degree(g.sub.prout.mcns, mode = "in") > 0 |
        name %in% start_types
    ]
  )

  # 4. Keep only vertices with out‐degree > 0 or in target_types
  g.sub.prout.mcns <- induced_subgraph(
    g.sub.prout.mcns,
    vids = V(g.sub.prout.mcns)[
      degree(g.sub.prout.mcns, mode = "out") > 0 |
        name %in% target_types
    ]
  )

  new_edges    <- ecount(g.sub.prout.mcns)
  new_vertices <- vcount(g.sub.prout.mcns)

  if (new_edges == prev_edges && new_vertices == prev_vertices) {
    message("Pruning converged: ", new_vertices, " vertices and ", new_edges, " edges remain")
    break
  }
}




library(RCy3)

# generate timestamp for unique naming
timestamp   <- format(Sys.time(), "%Y%m%d%H%M%S")
networkName <- paste0("path.simulated.activity", timestamp)
fileName    <- paste0(networkName, ".cx")

# create output folder if it does not exist
outputDir <- file.path(getwd(), "output", "networks")
if (! dir.exists(outputDir)) {
  dir.create(outputDir, recursive = TRUE)
}

# full paths
graphmlPath <- file.path(outputDir, fileName)

# 1. create the network in Cytoscape
cy_net <- createNetworkFromIgraph(
  g.sub.prout.mcns,
  title      = networkName,
  collection = "vAB3.PPN1.inputs.to.P1.and.similar"
)

# 2. export the network to GraphML
exportNetwork(
  filename = graphmlPath,
  type     = "CX"
)




```
```{r}
# 1. define which transmitters are excitatory vs inhibitory
excitatory <- c("acetylcholine", "glutamate", "serotonin", "dopamine", "octopamine")
inhibitory <- c("gaba")

# 2. pull out the neurotransmitter and name vectors
nt_vec     <- V(g.sub.prout.mcns)$nt
name_vec   <- V(g.sub.prout.mcns)$name

# 3. map each nt to +1/−1 (NA if unknown)
mapped     <- ifelse(
  nt_vec %in% excitatory,  1L,
  ifelse(nt_vec %in% inhibitory, -1L, 1L)
)

# 4. give that numeric vector the vertex names
names(mapped) <- name_vec
```


Graph pass
```{r}
adj.reduced <- as.matrix(as_adjacency_matrix(g.sub.prout.mcns, attr = "weight"))


nt <- mapped
empty_na <- array(0,dim = dim(adj.reduced))




#start
t0 <- zero_list <- setNames(
  as.numeric(rep(0, length(colnames(adj.reduced)))),
  colnames(adj.reduced)
)
t0[names(t0) %in% start_types] = 1

transmit0 = colSums(adj.reduced[names(t0[t0!=0]),]*nt[names(t0[t0!=0])])

t1 <- t0 + transmit0
t1[t1 %in% start_types] = 0

#step1
t1[names(t1) %in% start_types] = 1

transmit1 = colSums(adj.reduced[names(t1[t1!=0]),]*nt[names(t1[t1!=0])])

t2 <- t1 + transmit1
t2[t2 %in% start_types] = 0


#step2
t2[names(t2) %in% start_types] = 1

transmit2 = colSums(adj.reduced[names(t2[t2!=0]),]*nt[names(t2[t2!=0])])

t3 <- t2 + transmit2


```

code function
```{r}

g <- g.sub.prout.mcns

excitatory <- c("acetylcholine", "glutamate", "serotonin", "dopamine", "octopamine")
inhibitory <- c("gaba")

# 2. pull out the neurotransmitter and name vectors
nt_vec     <- V(g)$nt
name_vec   <- V(g)$name

# 3. map each nt to +1/−1 (NA if unknown)
mapped     <- ifelse(
  nt_vec %in% excitatory,  1L,
  ifelse(nt_vec %in% inhibitory, -1L, 1L)
)

# 4. give that numeric vector the vertex names
names(mapped) <- name_vec

adj.reduced <- as.matrix(as_adjacency_matrix(g, attr = "weight"))
t0 <- data.frame(
    setNames(
        as.list(rep(0, ncol(adj.reduced))),
        colnames(adj.reduced)
    ),
    check.names = FALSE
)
epochs=100
for (i in seq(1,epochs)){
if (i<=5){
t0[i,colnames(t0) %in% start] = 0.1}
transmit0 = colSums(adj.reduced[colnames(t0[i,t0[i,]!=0]),] * nt[colnames(t0[i,t0[i,]!=0])])
next_step <- (t0[i,]*0.8-0.1)+t(data.frame(transmit0))
t0<-rbind(t0,next_step)
rownames(t0)<-seq(1,dim(t0)[1])}
t0.normed <- sweep(t0, 2, V(g.sub.prout.mcns)$distance_to_start+1, FUN = "*") 


#plotting

timestamp  <- format(Sys.time(), "%Y%m%d%H%M%S")
graphName0 <- paste0("activity.heatmap.clustered_", timestamp)
graphName1 <- paste0("activity.trace_",            timestamp)
fileName0  <- paste0(graphName0, ".png")
fileName1  <- paste0(graphName1, ".png")

outputDir0 <- file.path(getwd(), "output", "activity.heatmap")
outputDir1 <- file.path(getwd(), "output", "activity.trace")
dir.create(outputDir0, recursive = TRUE, showWarnings = FALSE)
dir.create(outputDir1, recursive = TRUE, showWarnings = FALSE)

pngPath0 <- file.path(outputDir0, fileName0)
pngPath1 <- file.path(outputDir1, fileName1)

# 2. draw & save the clustered heatmap
png(filename = pngPath0, width = 2800, height = 3500, res = 300)
pheatmap(
  t(t0.normed),
  cluster_rows  = TRUE,
  cluster_cols  = FALSE,
  fontsize_row  = 4,
  fontsize_col  = 6,
  cellheight    = 4,
  cellwidth     = 4,
  main          = graphName0
)
dev.off()

# 3. draw & save the activity trace
series <- as.matrix(t0)
png(filename = pngPath1, width = 1500, height = 1000, res = 300)
matplot(
  series,
  type  = "l",
  lty   = 1,
  xaxt  = "n",
  xlab  = "Timestep",
  ylab  = "Value",
  main  = graphName1
)
axis(1, at = seq_len(nrow(series)), labels = seq_len(nrow(series)))
dev.off()

message(
  "Saved heatmap to: ", pngPath0, "\n",
  "Saved trace   to: ", pngPath1
)
```








